name: Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install go dependencies
        run: "go get all"
      - name: Run Tests
        run: "go test -v -race -coverprofile=coverage.txt -covermode=atomic ./... -p 1"
      - name: Report coverage
        run: "bash <(curl -s https://codecov.io/bash)"
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
